apiVersion: apps/v1
kind: Deployment
metadata:
  name: accommodations-backend
  namespace: accommodations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accommodations-backend
  template:
    metadata:
      labels:
        app: accommodations-backend
    spec:
      containers:
        - name: backend
          image: tammy38/renting-app-backend:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_PASSWORD



