apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: accommodations
data:
  default.conf: |
    server {
        listen 80;
    
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        client_max_body_size 100m;
        large_client_header_buffers 16 128k;
        client_header_buffer_size 128k;
    
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    
    #  Route for the frontend application
    location / {
        proxy_pass http://accommodations-frontend-service:80;   
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

    }

    # Route for the backend API
    location /api/ {
        proxy_pass http://accommodations-backend-service:9090;  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

    }
    }
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accommodations-renting-db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: tammy38


