#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: accommodations-config
#  namespace: accommodations
#data:
#  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accommodations-renting-db
#  SPRING_DATASOURCE_USERNAME: postgres
#  SPRING_DATASOURCE_PASSWORD: tammy38



apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: accommodations
data:
  default.conf: |
    server {
        listen 80;

        client_max_body_size 50m; # Adjust as necessary
        large_client_header_buffers 8 64k; # Adjust as necessary
        client_header_buffer_size 64k;

        # Route for the frontend application
    location / {
        proxy_pass http://accommodations-frontend-service:80;  # Frontend service
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route for the backend API
    location /api/ {
        proxy_pass http://accommodations-backend-service:9090;  # Backend service
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    }
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accommodations-renting-db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: tammy38

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: backend-config
#  namespace: accommodations
#data:
#  SPRING_APPLICATION_NAME: lab1
#  SPRING_JPA_HIBERNATE_DDL_AUTO: update
#  SPRING_JPA_SHOW_SQL: "true"
#  SPRING_THYMELEAF_CHECK_TEMPLATE_LOCATION: "false"
#  SPRING_JPA_OPEN_IN_VIEW: "false"
