apiVersion: v1
kind: Service
metadata:
  name: accommodations-frontend-service
  namespace: accommodations
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: accommodations-frontend
