apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accommodations-frontend-ingress
  namespace: accommodations
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: renting-app.local.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: accommodations-backend-service
                port:
                  number: 9090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accommodations-frontend-service
                port:
                  number: 80

