apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accommodations-ingress
  namespace: accommodations
  annotations:
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: renting-app.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accommodations-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: accommodations-backend-service
                port:
                  number: 9090
